package com.bean.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "BEAN".
 */
public class Bean implements Serializable{

    private Long id;
    private String name;
    private String data1;
    private String data2;
    private String data3;
    private String timeDetail;
    private java.util.Date now;

    public Bean() {
    }

    public Bean(Long id) {
        this.id = id;
    }

    public Bean(Long id, String name, String data1, String data2, String data3, String timeDetail, java.util.Date now) {
        this.id = id;
        this.name = name;
        this.data1 = data1;
        this.data2 = data2;
        this.data3 = data3;
        this.timeDetail = timeDetail;
        this.now = now;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getData1() {
        return data1;
    }

    public void setData1(String data1) {
        this.data1 = data1;
    }

    public String getData2() {
        return data2;
    }

    public void setData2(String data2) {
        this.data2 = data2;
    }

    public String getData3() {
        return data3;
    }

    public void setData3(String data3) {
        this.data3 = data3;
    }

    public String getTimeDetail() {
        return timeDetail;
    }

    public void setTimeDetail(String timeDetail) {
        this.timeDetail = timeDetail;
    }

    public java.util.Date getNow() {
        return now;
    }

    public void setNow(java.util.Date now) {
        this.now = now;
    }

}
